In [1]:
import numpy as np 
import pandas as pd 

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/math482-2024-2025-1-hw-04/sample_submission.csv
/kaggle/input/math482-2024-2025-1-hw-04/train.csv
/kaggle/input/math482-2024-2025-1-hw-04/test.csv

In [2]:
df_train = pd.read_csv("/kaggle/input/math482-2024-2025-1-hw-04/train.csv")
df_test = pd.read_csv("/kaggle/input/math482-2024-2025-1-hw-04/test.csv")

df_train.head()

,id,feature_01,feature_02,feature_03,feature_04,feature_05,feature_06,feature_07,feature_08,feature_09,...,feature_13,feature_14,feature_15,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,target
0,1,0.94,D2,B1,NaN,1.88,0.40,NaN,1.33,NaN,...,-3.64,r,1.27,-0.87,-1.20,0.29,A2,ad,0.34,1
1,2,6.02,D3,B1,1.0,1.12,0.33,0.25,1.96,xy,...,-3.02,s,0.86,0.11,-14.86,0.66,A2,ae,0.31,5
2,3,2.63,D1,B6,2.0,1.60,0.35,0.43,2.42,xy,...,-3.22,q,0.19,-6.30,-64.38,0.57,A5,ac,0.18,4
3,4,1.83,NaN,B4,1.0,0.98,0.44,0.15,2.09,xy,...,-2.85,s,1.41,-3.09,NaN,0.56,A1,aa,1.46,3
4,5,0.34,D3,B6,0.0,0.93,0.53,0.26,4.30,xy,...,-6.11,u,0.57,-3.28,-1.01,0.38,A3,ad,1.79,5

In [3]:
df_test.head()

,id,feature_01,feature_02,feature_03,feature_04,feature_05,feature_06,feature_07,feature_08,feature_09,...,feature_12,feature_13,feature_14,feature_15,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21
0,22501,NaN,D4,NaN,2.0,0.15,0.36,0.17,1.50,xy,...,-1.81,-4.31,p,NaN,-3.12,-1.91,19.85,A2,aa,NaN
1,22502,0.23,D1,B3,3.0,1.90,0.64,NaN,1.45,xy,...,-1.16,-3.55,s,3.12,NaN,0.61,0.10,A2,ac,0.30
2,22503,0.57,D1,B5,0.0,2.19,NaN,NaN,0.08,yy,...,-114.94,-2.95,r,0.72,0.24,0.15,0.29,A2,ad,4.06
3,22504,4.28,NaN,B5,NaN,0.94,NaN,0.27,1.57,NaN,...,-0.34,NaN,NaN,2.39,-5.27,-1.25,0.30,A1,ae,1.62
4,22505,0.90,D1,B5,1.0,1.42,0.61,0.45,0.25,xy,...,-0.10,-0.44,r,5.02,-3.27,-1.46,0.26,A4,NaN,NaN

# Preprocessing for the Train Set

Missing values, outliers, unconverted categorical features, irrelavent values mislead functions and hence the model which are created with the concern of generalizability. That's why, **data preprocessing** is the most important part of machine learning process.

**Null Values**

In [4]:
df_train.isnull().sum()

id               0
feature_01    2404
feature_02    2888
feature_03    2467
feature_04    2359
feature_05    2045
feature_06    2943
feature_07    2755
feature_08    1527
feature_09    2618
feature_10    2155
feature_11    2802
feature_12    2631
feature_13    3083
feature_14    1243
feature_15    1647
feature_16    2211
feature_17    3094
feature_18    1281
feature_19    1412
feature_20    1371
feature_21    1943
target           0
dtype: int64

In [5]:
# what is the total number of null values?

df_train.isnull().sum().sum()

46879

In [6]:
print("Mean value of each column:")

# Select only numeric columns and calculate the mean for each row
numeric_df = df_train.select_dtypes(include=["float64", "int64"])

# Calculate the mean values of each row
mean_values = numeric_df.mean(axis=0)

# Print the mean values
print(mean_values)

Mean value of each column:
id            11250.500000
feature_01        6.239823
feature_04        7.113022
feature_05        4.352539
feature_06        1.162647
feature_07        3.424100
feature_08       20.395801
feature_11       -4.883125
feature_12       -5.699943
feature_13      -22.232416
feature_15        9.371157
feature_16      -14.442898
feature_17       -7.817956
feature_18        2.188494
feature_21       16.879567
target            2.740044
dtype: float64

In [7]:
print("Mean value of each column:")
numeric_df_test = df_test.select_dtypes(include=["float64", "int64"])
mean_values_test = numeric_df_test.mean(axis=0)
print(mean_values_test)

Mean value of each column:
id            26250.500000
feature_01        6.001149
feature_04        7.725701
feature_05        4.531149
feature_06        1.068758
feature_07        3.545614
feature_08       21.636477
feature_11       -5.020546
feature_12       -5.700343
feature_13      -21.829043
feature_15        9.712448
feature_16      -15.035111
feature_17       -7.926942
feature_18        2.193616
feature_21       15.474935
dtype: float64

In the examination of the dataset, the column named as feature_04 has a different pattern compared the other columns with  numerical values. So, it is better to use the mode which is the value that appears most frequently in the column instead of the mean value of that column which is  7.725701.

In [8]:
df_train["feature_04"].mode()

df_train["feature_04"].fillna(0, inplace=True)

For others, missing values is filled with the mean (average) of each numeric column in the dataset.

In [9]:
df_train.fillna(numeric_df.mean()[:], inplace= True)

df_train.head(-1)

,id,feature_01,feature_02,feature_03,feature_04,feature_05,feature_06,feature_07,feature_08,feature_09,...,feature_13,feature_14,feature_15,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,target
0,1,0.94,D2,B1,0.0,1.880000,0.400000,3.4241,1.33,NaN,...,-3.64,r,1.27,-0.870000,-1.200000,0.29,A2,ad,0.340000,1
1,2,6.02,D3,B1,1.0,1.120000,0.330000,0.2500,1.96,xy,...,-3.02,s,0.86,0.110000,-14.860000,0.66,A2,ae,0.310000,5
2,3,2.63,D1,B6,2.0,1.600000,0.350000,0.4300,2.42,xy,...,-3.22,q,0.19,-6.300000,-64.380000,0.57,A5,ac,0.180000,4
3,4,1.83,NaN,B4,1.0,0.980000,0.440000,0.1500,2.09,xy,...,-2.85,s,1.41,-3.090000,-7.817956,0.56,A1,aa,1.460000,3
4,5,0.34,D3,B6,0.0,0.930000,0.530000,0.2600,4.30,xy,...,-6.11,u,0.57,-3.280000,-1.010000,0.38,A3,ad,1.790000,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22494,22495,1.10,D1,B5,0.0,1.350000,0.280000,0.1600,0.96,xy,...,-1.31,s,1.73,-14.442898,-0.460000,36.64,A1,aa,0.550000,2
22495,22496,2.48,D1,B2,1.0,2.430000,1.162647,0.4200,3.82,xx,...,-0.62,r,3.32,-5.370000,-2.720000,0.15,A2,ad,16.879567,4
22496,22497,4.05,D1,B3,0.0,1.000000,23.180000,0.2600,0.10,xy,...,-1.09,t,0.96,-2.240000,-0.220000,0.59,A1,ad,16.879567,3
22497,22498,7.43,NaN,B5,2.0,0.830000,1.162647,0.4400,0.22,xy,...,-5.14,s,2.13,0.040000,0.410000,0.37,NaN,ae,115.840000,3
22498,22499,6.09,D1,B5,1.0,4.352539,0.220000,0.3100,0.89,xy,...,-3.00,p,1.83,-4.090000,-137.020000,0.37,A4,aa,0.320000,1

However, we only dealt with the numerical values. There are also columns with categorical values which have null values to be filled. For this end, using the mode function is again the most efficient way concerning the limited number of values of categorical columns.

In [10]:
df_train.isnull().sum().sum()

14154

In [11]:
# Getting list of categorical variables

s = (df_train.dtypes == 'object')
object_cols = list(s[s].index)

print("Categorical variables:")
print(object_cols)

Categorical variables:
['feature_02', 'feature_03', 'feature_09', 'feature_10', 'feature_14', 'feature_19', 'feature_20']

In [12]:
df_train[object_cols].mode()

  feature_02 feature_03 feature_09 feature_10 feature_14 feature_19 feature_20
0         D1         B5         xy         C6          s         A1         ad

In [13]:
# categorical value assignment

# Filling missing values with the mode for each categorical column

for col in object_cols:
    mode_value = df_train[col].mode()[0]  # Get the mode
    df_train[col].fillna(mode_value, inplace=True)  # Fill NaNs with the mode

# Checking the result

print(df_train.isnull().sum())    # Should show 0 for all categorical columns

id            0
feature_01    0
feature_02    0
feature_03    0
feature_04    0
feature_05    0
feature_06    0
feature_07    0
feature_08    0
feature_09    0
feature_10    0
feature_11    0
feature_12    0
feature_13    0
feature_14    0
feature_15    0
feature_16    0
feature_17    0
feature_18    0
feature_19    0
feature_20    0
feature_21    0
target        0
dtype: int64

In [14]:
df_train.head()

,id,feature_01,feature_02,feature_03,feature_04,feature_05,feature_06,feature_07,feature_08,feature_09,...,feature_13,feature_14,feature_15,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,target
0,1,0.94,D2,B1,0.0,1.88,0.40,3.4241,1.33,xy,...,-3.64,r,1.27,-0.87,-1.200000,0.29,A2,ad,0.34,1
1,2,6.02,D3,B1,1.0,1.12,0.33,0.2500,1.96,xy,...,-3.02,s,0.86,0.11,-14.860000,0.66,A2,ae,0.31,5
2,3,2.63,D1,B6,2.0,1.60,0.35,0.4300,2.42,xy,...,-3.22,q,0.19,-6.30,-64.380000,0.57,A5,ac,0.18,4
3,4,1.83,D1,B4,1.0,0.98,0.44,0.1500,2.09,xy,...,-2.85,s,1.41,-3.09,-7.817956,0.56,A1,aa,1.46,3
4,5,0.34,D3,B6,0.0,0.93,0.53,0.2600,4.30,xy,...,-6.11,u,0.57,-3.28,-1.010000,0.38,A3,ad,1.79,5


**Outlier**

This is a data preprocessing step aimed at preparing the dataset for outlier detection and removal. By focusing on numeric columns, we can apply statistical methods to identify and handle outliers effectively, contributing to cleaner and more reliable data for analysis or modeling.

In [15]:
df = df_train.select_dtypes(include=["float64", "int64"]).copy()
# df = df_train.copy()
df.head()

,id,feature_01,feature_04,feature_05,feature_06,feature_07,feature_08,feature_11,feature_12,feature_13,feature_15,feature_16,feature_17,feature_18,feature_21,target
0,1,0.94,0.0,1.88,0.40,3.4241,1.33,-4.883125,-0.29,-3.64,1.27,-0.87,-1.200000,0.29,0.34,1
1,2,6.02,1.0,1.12,0.33,0.2500,1.96,-1.280000,-92.68,-3.02,0.86,0.11,-14.860000,0.66,0.31,5
2,3,2.63,2.0,1.60,0.35,0.4300,2.42,-0.520000,-1.93,-3.22,0.19,-6.30,-64.380000,0.57,0.18,4
3,4,1.83,1.0,0.98,0.44,0.1500,2.09,-2.790000,-1.24,-2.85,1.41,-3.09,-7.817956,0.56,1.46,3
4,5,0.34,0.0,0.93,0.53,0.2600,4.30,-1.130000,-1.53,-6.11,0.57,-3.28,-1.010000,0.38,1.79,5

In [16]:
from sklearn.neighbors import LocalOutlierFactor

In [17]:
clf = LocalOutlierFactor(n_neighbors = 20, contamination= 0.1)

In [18]:
clf.fit_predict(df)

array([ 1,  1,  1, ..., -1, -1,  1])

In [19]:
df_scores = clf.negative_outlier_factor_
df_scores[0:10]

array([-1.17418268, -2.50916447, -2.19616248, -1.13870185, -1.11479213,
       -2.78831383, -1.15562231, -1.0828661 , -1.99535812, -3.20935868])

In [20]:
# To see the range of score for all rows

np.sort(df_scores)[0:]

array([-11.74428967, -11.48381856, -11.32960354, ...,  -0.95692466,
        -0.95472518,  -0.95162496])

In [21]:
# trying different values to determine an eligible threshold 

threshold = np.sort(df_scores)[300]
threshold

-5.0142249284539355

In [22]:
df[df_scores==threshold]

,id,feature_01,feature_04,feature_05,feature_06,feature_07,feature_08,feature_11,feature_12,feature_13,feature_15,feature_16,feature_17,feature_18,feature_21,target
13277,13278,2.35,2.0,1.96,0.35,0.31,0.54,-1.03,-0.04,-0.07,9.371157,-190.69,-0.13,0.33,2.23,0

In [23]:
# These are the outliers to eliminate according to the chosen threshold

df[df_scores<threshold] # outliers

,id,feature_01,feature_04,feature_05,feature_06,feature_07,feature_08,feature_11,feature_12,feature_13,feature_15,feature_16,feature_17,feature_18,feature_21,target
10,11,0.04,186.16,5.520000,0.570000,0.2900,0.74,-4.883125,0.160000,-2.92,0.27,-3.070000,116.380000,0.34,16.879567,4
60,61,0.98,0.00,2.040000,1.162647,0.3400,1.53,-1.180000,0.000000,-0.64,190.75,-4.180000,0.650000,0.41,0.200000,2
68,69,0.15,372.33,2.770000,0.480000,0.2800,1.69,-1.040000,-5.699943,-6.46,7.41,-1.460000,-0.030000,0.43,2.220000,0
152,153,0.31,186.16,4.352539,0.290000,3.4241,0.21,-2.250000,-0.190000,-13.51,64.04,-14.442898,-0.660000,0.48,1.690000,0
292,293,222.62,0.00,0.410000,0.610000,0.3800,0.69,-4.883125,-3.260000,-4.65,0.91,-14.442898,-0.250000,0.32,1.170000,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22446,22447,0.39,2.00,2.120000,0.330000,0.4600,0.72,0.570000,-0.970000,-0.49,296.34,-14.442898,-7.817956,0.37,2.060000,4
22453,22454,245.79,1.00,1.390000,0.390000,0.6100,16.75,-0.450000,-1.670000,-3.39,2.85,-3.550000,0.950000,0.61,5.960000,3
22454,22455,2.95,2.00,0.450000,1.162647,0.0900,7.00,-4.780000,-2.080000,-3.92,257.51,-3.160000,-0.580000,0.48,0.860000,5
22469,22470,2.09,279.25,4.352539,0.320000,3.4241,2.24,-124.160000,-0.150000,-4.00,1.67,-14.442898,-2.200000,0.39,2.830000,3
22492,22493,262.51,0.00,3.160000,0.260000,0.2700,0.67,-2.040000,1.540000,-2.85,0.64,-4.570000,-1.140000,0.53,1.520000,1

In [24]:
outlier_tf = df_scores > threshold
outlier_tf

array([ True,  True,  True, ...,  True,  True,  True])

In [25]:
# getting a numerical DataFrame without outliers

new_df = df[ df_scores > threshold]
new_df

,id,feature_01,feature_04,feature_05,feature_06,feature_07,feature_08,feature_11,feature_12,feature_13,feature_15,feature_16,feature_17,feature_18,feature_21,target
0,1,0.94,0.0,1.880000,0.400000,3.4241,1.33,-4.883125,-0.29,-3.64,1.27,-0.87,-1.200000,0.29,0.340000,1
1,2,6.02,1.0,1.120000,0.330000,0.2500,1.96,-1.280000,-92.68,-3.02,0.86,0.11,-14.860000,0.66,0.310000,5
2,3,2.63,2.0,1.600000,0.350000,0.4300,2.42,-0.520000,-1.93,-3.22,0.19,-6.30,-64.380000,0.57,0.180000,4
3,4,1.83,1.0,0.980000,0.440000,0.1500,2.09,-2.790000,-1.24,-2.85,1.41,-3.09,-7.817956,0.56,1.460000,3
4,5,0.34,0.0,0.930000,0.530000,0.2600,4.30,-1.130000,-1.53,-6.11,0.57,-3.28,-1.010000,0.38,1.790000,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22495,22496,2.48,1.0,2.430000,1.162647,0.4200,3.82,-1.270000,0.67,-0.62,3.32,-5.37,-2.720000,0.15,16.879567,4
22496,22497,4.05,0.0,1.000000,23.180000,0.2600,0.10,0.350000,-1.77,-1.09,0.96,-2.24,-0.220000,0.59,16.879567,3
22497,22498,7.43,2.0,0.830000,1.162647,0.4400,0.22,-0.930000,-1.50,-5.14,2.13,0.04,0.410000,0.37,115.840000,3
22498,22499,6.09,1.0,4.352539,0.220000,0.3100,0.89,-1.390000,-2.14,-3.00,1.83,-4.09,-137.020000,0.37,0.320000,1
22499,22500,0.79,0.0,2.450000,1.162647,23.8700,0.86,-4.883125,-1.53,-4.84,0.46,-3.01,-80.070000,0.47,16.879567,3

In [26]:
# Getting categorical columns from the original DataFrame
categorical_cols = df_train.select_dtypes(include=["object"]).copy()

# Concatenating the new numerical DataFrame with categorical columns
# Reseting index for proper concatenation

new_df.reset_index(drop=True, inplace=True)
categorical_cols.reset_index(drop=True, inplace=True)

# Creating the updated DataFrame by concatenating

df_train = pd.concat([new_df, categorical_cols], axis=1).dropna()
df_train

,id,feature_01,feature_04,feature_05,feature_06,feature_07,feature_08,feature_11,feature_12,feature_13,...,feature_18,feature_21,target,feature_02,feature_03,feature_09,feature_10,feature_14,feature_19,feature_20
0,1.0,0.94,0.0,1.880000,0.400000,3.4241,1.33,-4.883125,-0.29,-3.64,...,0.29,0.340000,1.0,D2,B1,xy,C6,r,A2,ad
1,2.0,6.02,1.0,1.120000,0.330000,0.2500,1.96,-1.280000,-92.68,-3.02,...,0.66,0.310000,5.0,D3,B1,xy,C5,s,A2,ae
2,3.0,2.63,2.0,1.600000,0.350000,0.4300,2.42,-0.520000,-1.93,-3.22,...,0.57,0.180000,4.0,D1,B6,xy,C3,q,A5,ac
3,4.0,1.83,1.0,0.980000,0.440000,0.1500,2.09,-2.790000,-1.24,-2.85,...,0.56,1.460000,3.0,D1,B4,xy,C3,s,A1,aa
4,5.0,0.34,0.0,0.930000,0.530000,0.2600,4.30,-1.130000,-1.53,-6.11,...,0.38,1.790000,5.0,D3,B6,xy,C6,u,A3,ad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22194,22496.0,2.48,1.0,2.430000,1.162647,0.4200,3.82,-1.270000,0.67,-0.62,...,0.15,16.879567,4.0,D1,B6,xy,C3,u,A1,ae
22195,22497.0,4.05,0.0,1.000000,23.180000,0.2600,0.10,0.350000,-1.77,-1.09,...,0.59,16.879567,3.0,D1,B5,xy,C1,u,A1,ae
22196,22498.0,7.43,2.0,0.830000,1.162647,0.4400,0.22,-0.930000,-1.50,-5.14,...,0.37,115.840000,3.0,D3,B5,xy,C1,u,A2,ab
22197,22499.0,6.09,1.0,4.352539,0.220000,0.3100,0.89,-1.390000,-2.14,-3.00,...,0.37,0.320000,1.0,D1,B3,xy,C6,p,A6,ae
22198,22500.0,0.79,0.0,2.450000,1.162647,23.8700,0.86,-4.883125,-1.53,-4.84,...,0.47,16.879567,3.0,D1,B2,xy,C6,u,A1,ae

**Converting Categorical Data**

In [27]:
for col in object_cols:
    unique_values = df_train[col].unique()
    print(f"Unique values in '{col}': {unique_values}")

Unique values in 'feature_02': ['D2' 'D3' 'D1' 'D4']
Unique values in 'feature_03': ['B1' 'B6' 'B4' 'B5' 'B2' 'B3']
Unique values in 'feature_09': ['xy' 'xx' 'yx' 'yy']
Unique values in 'feature_10': ['C6' 'C5' 'C3' 'C2' 'C1' 'C4']
Unique values in 'feature_14': ['r' 's' 'q' 'u' 'p' 't']
Unique values in 'feature_19': ['A2' 'A5' 'A1' 'A3' 'A4' 'A6']
Unique values in 'feature_20': ['ad' 'ae' 'ac' 'aa' 'ab']

In [28]:
from sklearn.preprocessing import OrdinalEncoder

# Defining the ordinal categories for each feature 

ordinals = {
    'feature_02': ['D1', 'D2', 'D3', 'D4'], 
    'feature_03': ['B1', 'B2', 'B3', 'B4', 'B5', 'B6'], 
    'feature_10': ['C1', 'C2', 'C3', 'C4', 'C5', 'C6'],  
    'feature_19': ['A1', 'A2', 'A3', 'A4', 'A5', 'A6'],  
}

# Initialize the OrdinalEncoder with the defined categories

encoder = OrdinalEncoder(categories=[ordinals[feature] for feature in ordinals.keys()])

# Fit and transform the specified features

df_train[list(ordinals.keys())] = encoder.fit_transform(df_train[list(ordinals.keys())])

# Display the transformed DataFrame
df_train

,id,feature_01,feature_04,feature_05,feature_06,feature_07,feature_08,feature_11,feature_12,feature_13,...,feature_18,feature_21,target,feature_02,feature_03,feature_09,feature_10,feature_14,feature_19,feature_20
0,1.0,0.94,0.0,1.880000,0.400000,3.4241,1.33,-4.883125,-0.29,-3.64,...,0.29,0.340000,1.0,1.0,0.0,xy,5.0,r,1.0,ad
1,2.0,6.02,1.0,1.120000,0.330000,0.2500,1.96,-1.280000,-92.68,-3.02,...,0.66,0.310000,5.0,2.0,0.0,xy,4.0,s,1.0,ae
2,3.0,2.63,2.0,1.600000,0.350000,0.4300,2.42,-0.520000,-1.93,-3.22,...,0.57,0.180000,4.0,0.0,5.0,xy,2.0,q,4.0,ac
3,4.0,1.83,1.0,0.980000,0.440000,0.1500,2.09,-2.790000,-1.24,-2.85,...,0.56,1.460000,3.0,0.0,3.0,xy,2.0,s,0.0,aa
4,5.0,0.34,0.0,0.930000,0.530000,0.2600,4.30,-1.130000,-1.53,-6.11,...,0.38,1.790000,5.0,2.0,5.0,xy,5.0,u,2.0,ad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22194,22496.0,2.48,1.0,2.430000,1.162647,0.4200,3.82,-1.270000,0.67,-0.62,...,0.15,16.879567,4.0,0.0,5.0,xy,2.0,u,0.0,ae
22195,22497.0,4.05,0.0,1.000000,23.180000,0.2600,0.10,0.350000,-1.77,-1.09,...,0.59,16.879567,3.0,0.0,4.0,xy,0.0,u,0.0,ae
22196,22498.0,7.43,2.0,0.830000,1.162647,0.4400,0.22,-0.930000,-1.50,-5.14,...,0.37,115.840000,3.0,2.0,4.0,xy,0.0,u,1.0,ab
22197,22499.0,6.09,1.0,4.352539,0.220000,0.3100,0.89,-1.390000,-2.14,-3.00,...,0.37,0.320000,1.0,0.0,2.0,xy,5.0,p,5.0,ae
22198,22500.0,0.79,0.0,2.450000,1.162647,23.8700,0.86,-4.883125,-1.53,-4.84,...,0.47,16.879567,3.0,0.0,1.0,xy,5.0,u,0.0,ae

ONeHotEndoing is the best converting method to preserve the equal distances between target value and different categorical variables without order.

In [29]:
df_train = pd.get_dummies(df_train, columns= ["feature_09", "feature_14", "feature_20"], prefix= ["feature_09", "feature_14", "feature_20"])
df_train = df_train.astype({col: int for col in df_train.select_dtypes("bool")})
df_train

,id,feature_01,feature_04,feature_05,feature_06,feature_07,feature_08,feature_11,feature_12,feature_13,...,feature_14_q,feature_14_r,feature_14_s,feature_14_t,feature_14_u,feature_20_aa,feature_20_ab,feature_20_ac,feature_20_ad,feature_20_ae
0,1.0,0.94,0.0,1.880000,0.400000,3.4241,1.33,-4.883125,-0.29,-3.64,...,0,1,0,0,0,0,0,0,1,0
1,2.0,6.02,1.0,1.120000,0.330000,0.2500,1.96,-1.280000,-92.68,-3.02,...,0,0,1,0,0,0,0,0,0,1
2,3.0,2.63,2.0,1.600000,0.350000,0.4300,2.42,-0.520000,-1.93,-3.22,...,1,0,0,0,0,0,0,1,0,0
3,4.0,1.83,1.0,0.980000,0.440000,0.1500,2.09,-2.790000,-1.24,-2.85,...,0,0,1,0,0,1,0,0,0,0
4,5.0,0.34,0.0,0.930000,0.530000,0.2600,4.30,-1.130000,-1.53,-6.11,...,0,0,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22194,22496.0,2.48,1.0,2.430000,1.162647,0.4200,3.82,-1.270000,0.67,-0.62,...,0,0,0,0,1,0,0,0,0,1
22195,22497.0,4.05,0.0,1.000000,23.180000,0.2600,0.10,0.350000,-1.77,-1.09,...,0,0,0,0,1,0,0,0,0,1
22196,22498.0,7.43,2.0,0.830000,1.162647,0.4400,0.22,-0.930000,-1.50,-5.14,...,0,0,0,0,1,0,1,0,0,0
22197,22499.0,6.09,1.0,4.352539,0.220000,0.3100,0.89,-1.390000,-2.14,-3.00,...,0,0,0,0,0,0,0,0,0,1
22198,22500.0,0.79,0.0,2.450000,1.162647,23.8700,0.86,-4.883125,-1.53,-4.84,...,0,0,0,0,1,0,0,0,0,1

#  Preprocessing for The Test Data

In [30]:
# Filling missing values:

df_test["feature_04"].mode()


numeric_df_test = df_test.select_dtypes(include=["float64", "int64"])
mean_values_test = numeric_df_test.mean(axis=0)

df_test["feature_04"].fillna(0, inplace=True)


df_test.fillna(numeric_df.mean()[:], inplace= True)


df_test[object_cols].mode()

for col in object_cols:
    mode_value = df_test[col].mode()[0]  # Get the mode
    df_test[col].fillna(mode_value, inplace=True) 

df_test

,id,feature_01,feature_02,feature_03,feature_04,feature_05,feature_06,feature_07,feature_08,feature_09,...,feature_12,feature_13,feature_14,feature_15,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21
0,22501,6.239823,D4,B5,2.0,0.15,0.360000,0.1700,1.500000,xy,...,-1.81,-4.310000,p,9.371157,-3.120000,-1.91,19.850000,A2,aa,16.879567
1,22502,0.230000,D1,B3,3.0,1.90,0.640000,3.4241,1.450000,xy,...,-1.16,-3.550000,s,3.120000,-14.442898,0.61,0.100000,A2,ac,0.300000
2,22503,0.570000,D1,B5,0.0,2.19,1.162647,3.4241,0.080000,yy,...,-114.94,-2.950000,r,0.720000,0.240000,0.15,0.290000,A2,ad,4.060000
3,22504,4.280000,D1,B5,0.0,0.94,1.162647,0.2700,1.570000,xy,...,-0.34,-22.232416,s,2.390000,-5.270000,-1.25,0.300000,A1,ae,1.620000
4,22505,0.900000,D1,B5,1.0,1.42,0.610000,0.4500,0.250000,xy,...,-0.10,-0.440000,r,5.020000,-3.270000,-1.46,0.260000,A4,ad,16.879567
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7495,29996,6.080000,D1,B6,3.0,1.17,1.162647,0.3400,20.395801,xy,...,-0.83,-2.370000,r,3.030000,-4.220000,-1.96,0.260000,A3,ad,0.680000
7496,29997,2.760000,D3,B2,2.0,1.41,0.370000,0.2600,0.220000,xy,...,-3.53,-0.760000,q,213.230000,-0.820000,-131.24,0.380000,A2,ad,0.600000
7497,29998,0.040000,D3,B2,1.0,0.63,0.370000,0.4400,5.430000,xy,...,-38.83,-6.170000,r,7.090000,-2.010000,-1.46,0.390000,A1,aa,0.240000
7498,29999,1.030000,D1,B2,2.0,4.97,0.320000,18.7500,0.170000,xy,...,-0.84,-22.232416,u,0.970000,-3.340000,-1.30,2.188494,A2,ae,0.610000
7499,30000,0.600000,D1,B3,0.0,4.67,0.510000,0.3300,0.840000,xx,...,0.91,-3.370000,s,4.580000,-3.210000,-1.26,0.440000,A1,ae,1.460000

In [31]:
categorical_cols_test = df_test.select_dtypes(include=["object"]).copy()

for col in categorical_cols_test:
    unique_values = df_test[col].unique()
    print(f"Unique values in '{col}' in the testdata: {unique_values}")

Unique values in 'feature_02' in the testdata: ['D4' 'D1' 'D2' 'D3']
Unique values in 'feature_03' in the testdata: ['B5' 'B3' 'B6' 'B2' 'B1' 'B4']
Unique values in 'feature_09' in the testdata: ['xy' 'yy' 'xx' 'yx']
Unique values in 'feature_10' in the testdata: ['C6' 'C1' 'C2' 'C4' 'C3' 'C5']
Unique values in 'feature_14' in the testdata: ['p' 's' 'r' 'q' 't' 'u']
Unique values in 'feature_19' in the testdata: ['A2' 'A1' 'A4' 'A3' 'A6' 'A5']
Unique values in 'feature_20' in the testdata: ['aa' 'ac' 'ad' 'ae' 'ab']

In [32]:
# Converting Ordinals to Numericals

from sklearn.preprocessing import OrdinalEncoder


ordinals_test = {
    'feature_02': ['D1', 'D2', 'D3', 'D4'], 
    'feature_03': ['B1', 'B2', 'B3', 'B4', 'B5', 'B6'], 
    'feature_10': ['C1', 'C2', 'C3', 'C4', 'C5', 'C6'],  
    'feature_19': ['A1', 'A2', 'A3', 'A4', 'A5', 'A6'],  
}

encoder_test = OrdinalEncoder(categories=[ordinals_test[feature] for feature in ordinals_test.keys()])

df_test[list(ordinals_test.keys())] = encoder_test.fit_transform(df_test[list(ordinals_test.keys())])

# Converting Nominals to Numericals

df_test = pd.get_dummies(df_test, columns= ["feature_09", "feature_14", "feature_20"], prefix= ["feature_09", "feature_14", "feature_20"])
df_test = df_test.astype({col: int for col in df_test.select_dtypes("bool")})

df_test

,id,feature_01,feature_02,feature_03,feature_04,feature_05,feature_06,feature_07,feature_08,feature_10,...,feature_14_q,feature_14_r,feature_14_s,feature_14_t,feature_14_u,feature_20_aa,feature_20_ab,feature_20_ac,feature_20_ad,feature_20_ae
0,22501,6.239823,3.0,4.0,2.0,0.15,0.360000,0.1700,1.500000,5.0,...,0,0,0,0,0,1,0,0,0,0
1,22502,0.230000,0.0,2.0,3.0,1.90,0.640000,3.4241,1.450000,0.0,...,0,0,1,0,0,0,0,1,0,0
2,22503,0.570000,0.0,4.0,0.0,2.19,1.162647,3.4241,0.080000,5.0,...,0,1,0,0,0,0,0,0,1,0
3,22504,4.280000,0.0,4.0,0.0,0.94,1.162647,0.2700,1.570000,1.0,...,0,0,1,0,0,0,0,0,0,1
4,22505,0.900000,0.0,4.0,1.0,1.42,0.610000,0.4500,0.250000,0.0,...,0,1,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7495,29996,6.080000,0.0,5.0,3.0,1.17,1.162647,0.3400,20.395801,2.0,...,0,1,0,0,0,0,0,0,1,0
7496,29997,2.760000,2.0,1.0,2.0,1.41,0.370000,0.2600,0.220000,2.0,...,1,0,0,0,0,0,0,0,1,0
7497,29998,0.040000,2.0,1.0,1.0,0.63,0.370000,0.4400,5.430000,3.0,...,0,1,0,0,0,1,0,0,0,0
7498,29999,1.030000,0.0,1.0,2.0,4.97,0.320000,18.7500,0.170000,0.0,...,0,0,0,0,1,0,0,0,0,1
7499,30000,0.600000,0.0,2.0,0.0,4.67,0.510000,0.3300,0.840000,2.0,...,0,0,1,0,0,0,0,0,0,1

# **Model Tuning and Training**

In [33]:
# import operations of required libraries

import tensorflow as tf
from tensorflow.keras.models import  Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.utils import to_categorical

import warnings
from warnings import filterwarnings

warnings.filterwarnings('ignore', category=DeprecationWarning)
warnings.filterwarnings('ignore', category=FutureWarning)
warnings.filterwarnings('ignore', category=UserWarning)
filterwarnings('ignore')

In [34]:
X = df_train.drop("target", axis=1)
y = df_train[["target"]]

# validation set

from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(X, y, 
                                                    test_size=0.20, 
                                                    random_state = 99)
num_labels = len(np.unique(y_train))  # y : labels, classes
num_labels

# Converting y_train and y_val to one-hot encoded format

y_train = to_categorical(y_train, num_classes= num_labels)
y_val = to_categorical(y_val, num_classes= num_labels)

In [35]:
print(X_train.shape, " ", X_val.shape, " ")

(17759, 34)   (4440, 34)

In [36]:
y_train.shape, y_val.shape

((17759, 6), (4440, 6))

In [37]:
# describe the structure of the neural network

model = tf.keras.Sequential([
    tf.keras.layers.Dense(units=128, 
                          activation='relu',
                          name="layer1",
                          input_shape = (34,)), 
     Dropout(0.2),
    Dense(64, activation="relu"),
    Dropout(0.2),
    tf.keras.layers.Dense(units= num_labels,
                          activation='softmax', # we use sofmax function since there are classes more than two
                          name="output_layer")]
                            )

# inner structure for mathematical optimization

model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=[tf.keras.metrics.Precision(),
                       tf.keras.metrics.Recall(),
                       "accuracy"]
              )

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ layer1 (Dense)                       │ (None, 128)                 │           4,480 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 128)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 64)                  │           8,256 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ (None, 64)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ output_layer (Dense)                 │ (None, 6)                   │             390 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 13,126 (51.27 KB)

 Trainable params: 13,126 (51.27 KB)

 Non-trainable params: 0 (0.00 B)

In [38]:
history = model.fit(X_train, y_train, epochs=50, validation_data=(X_val, y_val), batch_size=32)

Epoch 1/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.2214 - loss: 243.2725 - precision: 0.2034 - recall: 0.1193 - val_accuracy: 0.2597 - val_loss: 1.6943 - val_precision: 0.4444 - val_recall: 9.0090e-04
Epoch 2/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2502 - loss: 2.0850 - precision: 0.1626 - recall: 0.0020 - val_accuracy: 0.2597 - val_loss: 1.6631 - val_precision: 0.5000 - val_recall: 4.5045e-04
Epoch 3/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2613 - loss: 1.7736 - precision: 0.2331 - recall: 0.0012 - val_accuracy: 0.2597 - val_loss: 1.6600 - val_precision: 0.6667 - val_recall: 9.0090e-04
Epoch 4/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2587 - loss: 1.6726 - precision: 0.4980 - recall: 0.0014 - val_accuracy: 0.2590 - val_loss: 1.6588 - val_precision: 0.2500 - val_recall: 4.5045e-04
Epoch 5/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2553 - loss: 1.6957 - precision: 0.3227 - recall: 8.0406e-04 - val_accuracy: 0.2592 - val_loss: 1.6580 - val_precision: 0.3750 - val_recall: 6.7568e-04
Epoch 6/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2620 - loss: 1.6782 - precision: 0.3933 - recall: 0.0014 - val_accuracy: 0.2592 - val_loss: 1.6582 - val_precision: 0.3750 - val_recall: 6.7568e-04
Epoch 7/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2627 - loss: 1.6698 - precision: 0.1567 - recall: 1.8459e-04 - val_accuracy: 0.2592 - val_loss: 1.6573 - val_precision: 0.5000 - val_recall: 2.2523e-04
Epoch 8/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2563 - loss: 1.6870 - precision: 0.2347 - recall: 3.1055e-04 - val_accuracy: 0.2592 - val_loss: 1.6572 - val_precision: 0.3333 - val_recall: 2.2523e-04
Epoch 9/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2562 - loss: 1.6696 - precision: 0.4362 - recall: 5.2497e-04 - val_accuracy: 0.2588 - val_loss: 1.6584 - val_precision: 0.2500 - val_recall: 2.2523e-04
Epoch 10/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2564 - loss: 1.6660 - precision: 0.8248 - recall: 0.0015 - val_accuracy: 0.2590 - val_loss: 1.6587 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 11/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2565 - loss: 1.6676 - precision: 0.6890 - recall: 9.6626e-04 - val_accuracy: 0.2592 - val_loss: 1.6599 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 12/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2635 - loss: 1.6630 - precision: 0.6751 - recall: 8.2019e-04 - val_accuracy: 0.2592 - val_loss: 1.6589 - val_precision: 0.2500 - val_recall: 2.2523e-04
Epoch 13/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2639 - loss: 1.6638 - precision: 0.6211 - recall: 7.5584e-04 - val_accuracy: 0.2590 - val_loss: 1.6591 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 14/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2625 - loss: 1.6643 - precision: 0.6740 - recall: 5.7083e-04 - val_accuracy: 0.2592 - val_loss: 1.6591 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 15/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2633 - loss: 1.6725 - precision: 0.5335 - recall: 8.0793e-04 - val_accuracy: 0.2592 - val_loss: 1.6589 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 16/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.2580 - loss: 1.6619 - precision: 0.6409 - recall: 5.2477e-04 - val_accuracy: 0.2590 - val_loss: 1.6591 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 17/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.2602 - loss: 1.6679 - precision: 0.7954 - recall: 6.4001e-04 - val_accuracy: 0.2590 - val_loss: 1.6607 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 18/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.2581 - loss: 1.6700 - precision: 0.4227 - recall: 5.7408e-04 - val_accuracy: 0.2590 - val_loss: 1.6624 - val_precision: 0.2500 - val_recall: 2.2523e-04
Epoch 19/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.2585 - loss: 1.6674 - precision: 0.7097 - recall: 7.7208e-04 - val_accuracy: 0.2592 - val_loss: 1.6603 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 20/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2565 - loss: 1.6742 - precision: 0.7027 - recall: 4.2142e-04 - val_accuracy: 0.2586 - val_loss: 1.6609 - val_precision: 0.1429 - val_recall: 2.2523e-04
Epoch 21/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2589 - loss: 1.6721 - precision: 0.7381 - recall: 0.0013 - val_accuracy: 0.2592 - val_loss: 1.6635 - val_precision: 0.1429 - val_recall: 2.2523e-04
Epoch 22/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2476 - loss: 1.6656 - precision: 0.5383 - recall: 7.9133e-04 - val_accuracy: 0.2590 - val_loss: 1.6623 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 23/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.2630 - loss: 1.6616 - precision: 0.6546 - recall: 8.2226e-04 - val_accuracy: 0.2590 - val_loss: 1.6635 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 24/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2626 - loss: 1.6655 - precision: 0.4776 - recall: 4.9715e-04 - val_accuracy: 0.2590 - val_loss: 1.6681 - val_precision: 0.3636 - val_recall: 9.0090e-04
Epoch 25/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2593 - loss: 1.6689 - precision: 0.6555 - recall: 8.9104e-04 - val_accuracy: 0.2592 - val_loss: 1.6628 - val_precision: 0.2000 - val_recall: 2.2523e-04
Epoch 26/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2606 - loss: 1.6683 - precision: 0.6585 - recall: 9.6392e-04 - val_accuracy: 0.2592 - val_loss: 1.6617 - val_precision: 0.2500 - val_recall: 2.2523e-04
Epoch 27/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2577 - loss: 1.6636 - precision: 0.6346 - recall: 6.3659e-04 - val_accuracy: 0.2592 - val_loss: 1.6687 - val_precision: 0.3333 - val_recall: 9.0090e-04
Epoch 28/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2626 - loss: 1.6649 - precision: 0.4538 - recall: 6.2618e-04 - val_accuracy: 0.2592 - val_loss: 1.6658 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 29/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2588 - loss: 1.6638 - precision: 0.9099 - recall: 0.0011 - val_accuracy: 0.2592 - val_loss: 1.6699 - val_precision: 0.1429 - val_recall: 2.2523e-04
Epoch 30/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2581 - loss: 1.6662 - precision: 0.6971 - recall: 0.0012 - val_accuracy: 0.2590 - val_loss: 1.6704 - val_precision: 0.1667 - val_recall: 2.2523e-04
Epoch 31/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2603 - loss: 1.6657 - precision: 0.6271 - recall: 8.2228e-04 - val_accuracy: 0.2590 - val_loss: 1.6726 - val_precision: 0.1667 - val_recall: 2.2523e-04
Epoch 32/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2632 - loss: 1.6695 - precision: 0.6904 - recall: 7.7903e-04 - val_accuracy: 0.2590 - val_loss: 1.6705 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 33/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2568 - loss: 1.6696 - precision: 0.7530 - recall: 7.6309e-04 - val_accuracy: 0.2590 - val_loss: 1.6646 - val_precision: 0.3333 - val_recall: 4.5045e-04
Epoch 34/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2623 - loss: 1.7009 - precision: 0.7674 - recall: 0.0011 - val_accuracy: 0.2592 - val_loss: 1.6691 - val_precision: 0.3333 - val_recall: 4.5045e-04
Epoch 35/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2603 - loss: 1.6673 - precision: 0.9673 - recall: 0.0011 - val_accuracy: 0.2590 - val_loss: 1.6747 - val_precision: 0.3333 - val_recall: 6.7568e-04
Epoch 36/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2586 - loss: 1.6636 - precision: 0.7030 - recall: 9.1333e-04 - val_accuracy: 0.2590 - val_loss: 1.6692 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 37/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2615 - loss: 1.6683 - precision: 0.6341 - recall: 6.0437e-04 - val_accuracy: 0.2590 - val_loss: 1.6780 - val_precision: 0.1111 - val_recall: 2.2523e-04
Epoch 38/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.2624 - loss: 1.6630 - precision: 0.7800 - recall: 0.0012 - val_accuracy: 0.2583 - val_loss: 1.6756 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 39/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2623 - loss: 1.6634 - precision: 0.7214 - recall: 9.4353e-04 - val_accuracy: 0.2592 - val_loss: 1.6742 - val_precision: 0.2857 - val_recall: 4.5045e-04
Epoch 40/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2559 - loss: 1.6678 - precision: 0.7763 - recall: 9.7917e-04 - val_accuracy: 0.2592 - val_loss: 1.6781 - val_precision: 0.3750 - val_recall: 6.7568e-04
Epoch 41/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2612 - loss: 1.6625 - precision: 0.8521 - recall: 7.9218e-04 - val_accuracy: 0.2592 - val_loss: 1.6769 - val_precision: 0.3333 - val_recall: 6.7568e-04
Epoch 42/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2582 - loss: 1.6612 - precision: 0.7822 - recall: 8.8783e-04 - val_accuracy: 0.2590 - val_loss: 1.6728 - val_precision: 0.1250 - val_recall: 2.2523e-04
Epoch 43/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2591 - loss: 1.6650 - precision: 0.7680 - recall: 9.5444e-04 - val_accuracy: 0.2590 - val_loss: 1.6788 - val_precision: 0.3333 - val_recall: 4.5045e-04
Epoch 44/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2619 - loss: 1.6623 - precision: 0.7086 - recall: 6.3555e-04 - val_accuracy: 0.2590 - val_loss: 1.6801 - val_precision: 0.2500 - val_recall: 4.5045e-04
Epoch 45/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2566 - loss: 1.6638 - precision: 0.7239 - recall: 0.0011 - val_accuracy: 0.2590 - val_loss: 1.6803 - val_precision: 0.2857 - val_recall: 4.5045e-04
Epoch 46/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2561 - loss: 1.6641 - precision: 0.8440 - recall: 0.0010 - val_accuracy: 0.2590 - val_loss: 1.6840 - val_precision: 0.3000 - val_recall: 6.7568e-04
Epoch 47/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2577 - loss: 1.6698 - precision: 0.8206 - recall: 0.0014 - val_accuracy: 0.2592 - val_loss: 1.6881 - val_precision: 0.3846 - val_recall: 0.0011
Epoch 48/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2571 - loss: 1.6707 - precision: 0.6944 - recall: 0.0011 - val_accuracy: 0.2588 - val_loss: 1.6910 - val_precision: 0.1111 - val_recall: 2.2523e-04
Epoch 49/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2607 - loss: 1.6693 - precision: 0.9153 - recall: 0.0017 - val_accuracy: 0.2588 - val_loss: 1.7023 - val_precision: 0.1000 - val_recall: 2.2523e-04
Epoch 50/50
555/555 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2610 - loss: 1.6683 - precision: 0.8425 - recall: 8.7721e-04 - val_accuracy: 0.2592 - val_loss: 1.6923 - val_precision: 0.2857 - val_recall: 4.5045e-04

Let's examine a random state on the validation set

In [39]:
import random

random_index = random.randint(0,len(X_val)-1)
random_index

2286

In [40]:
test_data = X_val.iloc[random_index] # random  selection
test_data

id               18787.0000
feature_01           0.3100
feature_04           0.0000
feature_05           2.0500
feature_06           0.2600
feature_07           3.4241
feature_08           1.1100
feature_11          -1.3300
feature_12         -23.8200
feature_13          -2.5100
feature_15           1.5800
feature_16          -1.1100
feature_17          -3.9000
feature_18           0.2900
feature_21           1.7900
feature_02           0.0000
feature_03           4.0000
feature_10           2.0000
feature_19           5.0000
feature_09_xx        0.0000
feature_09_xy        1.0000
feature_09_yx        0.0000
feature_09_yy        0.0000
feature_14_p         0.0000
feature_14_q         0.0000
feature_14_r         0.0000
feature_14_s         1.0000
feature_14_t         0.0000
feature_14_u         0.0000
feature_20_aa        0.0000
feature_20_ab        0.0000
feature_20_ac        0.0000
feature_20_ad        1.0000
feature_20_ae        0.0000
Name: 18539, dtype: float64

In [41]:
label = y_val[random_index] # the label of that row
label

array([0., 0., 1., 0., 0., 0.])

In [42]:
test_data = test_data.values.reshape(1,-1)

probability = model.predict(test_data)
probability

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step

array([[0.0984282 , 0.23700073, 0.08579037, 0.24914308, 0.07105857,
        0.25857905]], dtype=float32)

In [43]:
predicted_classes = np.argmax(probability)
predicted_classes

5

In [44]:
y_val_pred = model.predict(X_val)
y_val_pred

139/139 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

array([[0.09842819, 0.23700072, 0.08579037, 0.24914305, 0.07105857,
        0.25857902],
       [0.09842819, 0.23700072, 0.08579037, 0.24914305, 0.07105857,
        0.25857902],
       [0.09842819, 0.23700072, 0.08579037, 0.24914305, 0.07105857,
        0.25857902],
       ...,
       [0.09842819, 0.23700072, 0.08579037, 0.24914305, 0.07105857,
        0.25857902],
       [0.09842819, 0.23700072, 0.08579037, 0.24914305, 0.07105857,
        0.25857902],
       [0.09842819, 0.23700072, 0.08579037, 0.24914305, 0.07105857,
        0.25857902]], dtype=float32)

In [45]:
predictions = model.predict(df_test)
predictions

235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

array([[0.09842819, 0.23700072, 0.08579037, 0.24914305, 0.07105857,
        0.25857902],
       [0.09842819, 0.23700072, 0.08579037, 0.24914305, 0.07105857,
        0.25857902],
       [0.09842819, 0.23700072, 0.08579037, 0.24914305, 0.07105857,
        0.25857902],
       ...,
       [0.0984282 , 0.23700075, 0.08579037, 0.24914308, 0.07105858,
        0.25857905],
       [0.0984282 , 0.23700075, 0.08579037, 0.24914308, 0.07105858,
        0.25857905],
       [0.0984282 , 0.23700075, 0.08579037, 0.24914308, 0.07105858,
        0.25857905]], dtype=float32)

In [46]:
predicted_classes = np.argmax(predictions, axis=1)
output_df = pd.DataFrame({
    "id": df_test["id"],
    "target": predicted_classes
})

output_df

         id  target
0     22501       5
1     22502       5
2     22503       5
3     22504       5
4     22505       5
...     ...     ...
7495  29996       5
7496  29997       5
7497  29998       5
7498  29999       5
7499  30000       5

[7500 rows x 2 columns]

(I do not know how to scale the data, yet. I guess that this absent part of the preprocessing causes the all outcomes of the test data to be 5.)

In [47]:
output_df.to_csv('submission.csv', index=False)
print("done")

done